# enisi.tech store -> port 8085
services:
  store:
    build:
      context: .
      args:
        PUBLIC_SUPABASE_URL: "https://supabase.shabanejupi.tech"
        PUBLIC_SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiYW5vbiIsImlzcyI6InN1cGFiYXNlIiwiaWF0IjoxNzgyOTc2Njk3LCJleHAiOjIwOTgzMzY2OTd9.EOuDpESKK-h3ByFPvfTzG5FjATx6W16vZoP6vyI8r94"
    image: enisi-store
    container_name: enisi_store
    restart: unless-stopped
    ports: ["8085:80"]
