using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KosovaPOS.Models
{
    public enum AlertType
    {
        LowStock             = 0,
        OverdueDebt          = 1,
        LicenseExpiry        = 2,
        DailyRevenueBelow    = 3,
        OverdueRental        = 4,
        CustomAlert          = 5
    }

    /// <summary>
    /// Stores per-alert thresholds and delivery preferences.
    /// Seed default rows created by the Sprint 7/8 migration.
    /// </summary>
    [Table("AlertConfigs")]
    public class AlertConfig
    {
        [Key]
        public int Id { get; set; }

        public AlertType Type { get; set; }

        [Required, StringLength(200)]
        public string Name { get; set; } = "";

        [StringLength(500)]
        public string? Description { get; set; }

        /// <summary>
        /// Meaning depends on AlertType:
        ///   LowStock          → minimum stock quantity
        ///   OverdueDebt       → overdue days threshold
        ///   LicenseExpiry     → days-before-expiry warning
        ///   DailyRevenueBelow → daily revenue floor (€)
        ///   OverdueRental     → overdue days threshold
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal Threshold { get; set; } = 5;

        public bool IsEnabled { get; set; } = true;

        /// <summary>Also send an email via Resend API when triggered.</summary>
        public bool SendEmail { get; set; }

        [StringLength(200)]
        public string? EmailRecipient { get; set; }

        public DateTime? LastTriggered { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }

    /// <summary>
    /// In-app notification inbox — generated by NotificationService when
    /// an AlertConfig threshold is crossed.
    /// </summary>
    [Table("NotificationItems")]
    public class NotificationItem
    {
        [Key]
        public int Id { get; set; }

        [Required, StringLength(200)]
        public string Title { get; set; } = "";

        [Required, StringLength(1000)]
        public string Message { get; set; } = "";

        public AlertType Type { get; set; }

        public bool IsRead { get; set; }

        /// <summary>
        /// Optional window key that should open when the user acts on this alert
        /// (e.g., "Stock", "Finance").
        /// </summary>
        [StringLength(100)]
        public string? ActionWindow { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}
